name: Deploy Flask App (Local + ngrok)

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  
      
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      
      - name: Set environment variables
        run: |
          echo "WORLD_APP_CLIENT_ID=${{ secrets.WORLD_APP_CLIENT_ID }}" >> $GITHUB_ENV
          echo "WORLD_APP_CLIENT_SECRET=${{ secrets.WORLD_APP_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "WORLD_APP_REDIRECT_URI=${{ secrets.WORLD_APP_REDIRECT_URI }}" >> $GITHUB_ENV
      
      
      - name: Deployment complete
      run: |
        echo "✅ App desplegada en: https://ganastrx4.github.io/chc-flask-app"

